import { CalendarDays, ChevronDown, ArrowUpRight, Info, Beef, ShieldCheck, Syringe, ScanLine, Search, Check, X, CircleHelp, type LucideIcon } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { dashboard, type Verification } from '@/lib/ioternak/data';
import type { ReactNode } from 'react';
export type Tone='info'|'success'|'warning'|'rfid'|'danger';
export function StatusBadge({children,tone='success',dot=false}:{children:ReactNode;tone?:Tone;dot?:boolean}) { return <span className={`badge tone-${tone}`}>{dot && <span className="h-1 w-1 rounded-full bg-current"/>}{children}</span>; }
export function PageHeading({title,subtitle,action}:{title:string;subtitle:string;action?:ReactNode}) { return <div className="page-heading"><div className="min-w-0"><h1>{title}</h1><p>{subtitle}</p></div>{action || <div className="date-control"><CalendarDays size={13}/><span>Senin, 05 Oktober 2026</span><ChevronDown size={12}/></div>}</div>; }
export function PanelHeading({title,subtitle,action}:{title:string;subtitle?:string;action?:ReactNode}) { return <div className="panel-heading"><div className="min-w-0"><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action}</div>; }
export function StatCard({label,value,unit,icon:Icon,tone,trend,positive=true}:{label:string;value:string|number;unit:string;icon:LucideIcon;tone:Tone;trend:string;positive?:boolean}) { return <div className="stat-card"><div className="stat-top"><span>{label}</span><div className={`stat-icon tone-${tone}`}><Icon size={17} strokeWidth={1.7}/></div></div><div className="stat-number">{value}</div><p className="stat-unit">{unit}</p><div className="stat-trend">{positive?<ArrowUpRight size={11} className="text-success"/>:<Info size={11} className="text-warning"/>}<span>{trend}</span></div></div>; }
export function OverviewStats({monitor=false}:{monitor?:boolean}) { return <div className="stats-grid"><StatCard label="Total Hewan" value="1,248" unit="hewan terdaftar" icon={Beef} tone="info" trend="+24 hewan bulan ini"/><StatCard label="Sudah Divaksin" value="1,086" unit="hewan terverifikasi" icon={ShieldCheck} tone="success" trend="87% dari total hewan"/><StatCard label="Belum Divaksin" value={dashboard.unvaccinated} unit="perlu pemeriksaan" icon={Syringe} tone="warning" trend="Prioritas vaksinasi berikutnya" positive={false}/><StatCard label={monitor?'Perlu Pemeriksaan':'Verifikasi Hari Ini'} value={monitor?42:86} unit={monitor?'jadwal booster mendatang':'pemeriksaan RFID'} icon={ScanLine} tone="rfid" trend={monitor?'Pemeriksaan oleh petugas':' +12 dari hari sebelumnya'}/></div>; }
export function SearchBar({value,onChange,placeholder='Cari ID RFID atau jenis hewan...'}:{value:string;onChange:(s:string)=>void;placeholder?:string}) { return <label className="search-field"><Search size={16}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></label>; }
export function FilterButton({active,onClick}:{active?:boolean;onClick:()=>void}) { return <Button variant={active?'secondary':'outline'} onClick={onClick} size="sm"><ChevronDown size={13}/>Filter</Button>; }
export function VerificationResult({result,large=false}:{result:Verification;large?:boolean}) { const eligible=result.eligible; return <div className={`result ${eligible?'':'rejected'} ${large?'large':''}`} role="status"><div className="result-title">{eligible?<Check size={large?43:27}/>:<X size={large?43:27}/>} {eligible?'LAYAK':'DITOLAK'}</div><p className={large?'text-center':''}>{result.reason}</p></div>; }
export function PageFooter() { return <footer className="page-footer"><span>© 2026 IoTernak. Smart Livestock System.</span><span className="flex items-center gap-2"><CircleHelp size={11}/>Verifikasi vaksin & monitoring pencegahan PMK</span></footer>; }
