import { Link } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowUpRight, ShieldCheck, Syringe, Clock, ChartNoAxesColumn, Download, FileText, Radio, Check, ArrowLeft, Users, Save, Info } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';
import { PageHeading,OverviewStats,PanelHeading,StatusBadge,PageFooter,StatCard,VerificationResult,SearchBar } from './common';
import { RFIDScannerCard } from './scanner';
import { ChartCard,VaccinationChart } from './charts';
import { ActivityTable,AnimalTable,VaccinationTable } from './tables';
import { useLivestock } from './store';
import { verifyAnimal,downloadCSV,type Animal } from '@/lib/ioternak/data';
import cowPhoto from '@/assets/cow-profile.jpg';
export function OverviewPage(){return <><PageHeading title="Overview" subtitle="Monitor data hewan, status vaksinasi, dan hasil verifikasi RFID."/><OverviewStats/><div className="dashboard-middle"><RFIDScannerCard/><ChartCard/></div><ActivityTable/><div className="bottom-grid"><UpcomingVaccinations/><MonitoringSummary/></div><PageFooter/></>;}
function UpcomingVaccinations(){return <section className="panel"><PanelHeading title="Jadwal Vaksinasi Mendatang" action={<Button asChild variant="ghost" size="sm" className="text-[10px]"><Link to="/vaksinasi">Lihat Jadwal<ArrowUpRight/></Link></Button>}/><div className="schedule-list">{[{day:'08',title:'Vaksinasi PMK & Booster',info:'2 hewan · Sapi',tone:'warning' as const},{day:'12',title:'Vaksinasi PMK',info:'1 hewan · Sapi',tone:'info' as const}].map(s=><div className="schedule-item" key={s.day}><div className="schedule-date"><strong>{s.day}</strong>OKT</div><div><h3>{s.title}</h3><p>{s.info}</p></div><StatusBadge tone={s.tone}>Terjadwal</StatusBadge></div>)}</div></section>;}
function MonitoringSummary(){return <section className="panel"><PanelHeading title="Monitoring Pencegahan PMK" action={<ShieldCheck size={17} className="text-success"/>}/><div className="monitor-summary"><div className="flex justify-between text-[11px]"><span className="text-muted-foreground">Cakupan verifikasi vaksin</span><strong className="text-success">87%</strong></div><div className="summary-progress"><div className="summary-progress-fill"/></div><p className="note">Verifikasi vaksin mendukung pencegahan PMK. Pemeriksaan kesehatan tetap dilakukan oleh petugas atau dokter hewan.</p></div></section>;}
export function VerificationPage(){return <><PageHeading title="Verifikasi RFID" subtitle="Identifikasi hewan dan verifikasi status vaksinasi melalui tag RFID."/><div className="dashboard-middle"><div><RFIDScannerCard full/></div><ChartCard/></div><ActivityTable/><PageFooter/></>;}
export function AnimalsPage({query,filter,onQuery,onFilter}:{query:string;filter:string;onQuery:(s:string)=>void;onFilter:(s:string)=>void}){return <><PageHeading title="Data Hewan" subtitle="Kelola informasi hewan yang terdaftar dalam sistem IoTernak."/><AnimalTable query={query} setQuery={onQuery} filter={filter} setFilter={onFilter}/><PageFooter/></>;}
export function VaccinationPage(){return <><PageHeading title="Vaksinasi" subtitle="Pantau cakupan vaksinasi dan jadwal perlindungan hewan."/><div className="stats-grid"><StatCard label="Sudah Divaksin" value="1,086" unit="hewan" icon={ShieldCheck} tone="success" trend="87% dari seluruh hewan"/><StatCard label="Belum Divaksin" value="162" unit="hewan" icon={Syringe} tone="warning" trend="Prioritas vaksinasi" positive={false}/><StatCard label="Perlu Booster" value="42" unit="hewan" icon={Clock} tone="rfid" trend="Jadwal vaksin mendatang" positive={false}/><StatCard label="Cakupan Vaksinasi" value="87%" unit="hewan terdaftar" icon={ChartNoAxesColumn} tone="info" trend="+5.2% bulan ini"/></div><div className="dashboard-middle"><VaccinationChart/><ChartCard/></div><VaccinationTable/><PageFooter/></>;}
export function PMKPage(){return <><PageHeading title="Status PMK" subtitle="Monitoring pencegahan PMK berdasarkan status verifikasi vaksin."/><OverviewStats monitor/><div className="dashboard-middle"><div><MonitoringSummary/><div className="panel p-6 mt-6"><div className="flex items-center gap-2 mb-3"><Info size={17} className="text-info"/><h2 className="font-semibold text-sm">Status verifikasi, bukan diagnosis</h2></div><p className="note">RFID mengidentifikasi hewan dan memeriksa catatan vaksinasi. Status LAYAK tidak menyatakan hewan bebas PMK. Jika terdapat gejala seperti luka mulut, air liur berlebih, atau pincang, segera hubungi dokter hewan untuk pemeriksaan.</p></div></div><ChartCard/></div><VaccinationTable/><PageFooter/></>;}
export function ActivityPage({history=false,query,onQuery}:{history?:boolean;query:string;onQuery:(s:string)=>void}){const {activities}=useLivestock();return <><PageHeading title={history?'Riwayat Pemeriksaan':'Aktivitas RFID'} subtitle="Telusuri hasil verifikasi vaksin dan aktivitas pemindaian RFID."/><div className="toolbar"><SearchBar value={query} onChange={onQuery} placeholder="Cari ID RFID, jenis hewan, atau petugas..."/><Button variant="outline" size="sm" onClick={()=>downloadCSV('ioternak-aktivitas.csv',[['ID RFID','Jenis','Tanggal','Hasil','Petugas'],...activities.map(a=>[a.animalId,a.type,a.checkedAt,a.eligible?'LAYAK':'DITOLAK',a.officer])])}><Download/>Ekspor CSV</Button></div><ActivityTable all query={query}/><PageFooter/></>;}
export function AnimalProfile({animal}:{animal:Animal}){return <section className="panel animal-profile">{animal.type==='Sapi'?<img className="animal-photo" src={cowPhoto} width={768} height={768} loading="lazy" alt="Foto ilustrasi sapi Brahman"/>:<div className="tone-info h-40 rounded-lg flex flex-col justify-center items-center gap-3"><span className="text-3xl">🐐</span><span className="text-xs">Kambing</span></div>}<div className="flex justify-between items-center"><h2 className="font-semibold text-sm">Profil Hewan</h2><StatusBadge tone="info">{animal.type}</StatusBadge></div><dl className="animal-facts">{[['ID RFID',animal.id],['Nomor Tag',animal.tag],['Jenis',animal.type],['Jenis Kelamin',animal.sex],['Umur',`${animal.age} Tahun`]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>;}
export function VaccinationTimeline({animal}:{animal:Animal}){return <section className="panel"><PanelHeading title="Riwayat Vaksinasi" subtitle="Catatan pemberian vaksin PMK"/><div className="timeline">{animal.vaccinated?[animal.lastVaccine,...(animal.id==='RFID-001245'?['15 Februari 2026']:[])].map(date=><div className="timeline-item" key={date}><h3>{date}</h3><p>Vaksin PMK · Petugas: Admin</p><StatusBadge tone="success"><Check size={10}/>Berhasil</StatusBadge></div>):<p className="note">Belum ada catatan vaksinasi untuk hewan ini.</p>}</div></section>;}
export function AnimalDetailPage({id}:{id:string}){const {animals}=useLivestock();const animal=animals.find(a=>a.id===id);if(!animal)return <><PageHeading title="Hewan Tidak Ditemukan" subtitle="ID RFID tidak terdaftar dalam data contoh."/><Button asChild variant="outline"><Link to="/data-hewan" search={{q:'',filter:'all'}}><ArrowLeft/>Kembali ke Data Hewan</Link></Button></>;return <><PageHeading title="Detail Hewan" subtitle={`${animal.id} · Informasi identitas dan catatan vaksinasi`} action={<Button variant="outline" size="sm" asChild><Link to="/data-hewan" search={{q:'',filter:'all'}}><ArrowLeft/>Data Hewan</Link></Button>}/><div className="detail-grid"><AnimalProfile animal={animal}/><div className="grid gap-6 content-start"><section className="panel p-6"><h2 className="text-xs font-semibold text-muted-foreground mb-4">STATUS VAKSIN PMK</h2><VerificationResult result={verifyAnimal(animal)}/><div className="animal-facts"><div><dt>Vaksin terakhir</dt><dd>{animal.lastVaccine||'Belum ada catatan'}</dd></div><div><dt>Jadwal berikutnya</dt><dd>{animal.nextVaccine}</dd></div></div></section><VaccinationTimeline animal={animal}/></div></div><PageFooter/></>;}
export function ReportsPage(){const {animals,activities}=useLivestock();const [downloaded,setDownloaded]=useState('');return <><PageHeading title="Laporan" subtitle="Ringkasan data hewan, vaksinasi, dan verifikasi RFID."/><div className="report-grid">{[{title:'Data Hewan',icon:FileText,info:`${animals.length} catatan hewan contoh`,rows:[['ID RFID','Jenis','Status'],...animals.map(a=>[a.id,a.type,a.vaccinated?'Sudah':'Belum'])]},{title:'Vaksinasi',icon:Syringe,info:'Catatan dan jadwal vaksinasi',rows:[['ID RFID','Vaksin Terakhir','Jadwal'],...animals.map(a=>[a.id,a.lastVaccine||'Belum',a.nextVaccine])]},{title:'Aktivitas RFID',icon:Radio,info:`${activities.length} pemeriksaan contoh`,rows:[['ID RFID','Tanggal','Hasil'],...activities.map(a=>[a.animalId,a.checkedAt,a.eligible?'LAYAK':'DITOLAK'])]}].map(r=><section key={r.title} className="panel report-card"><div className="stat-icon tone-info mb-4"><r.icon size={18}/></div><h2 className="font-semibold text-sm">{r.title}</h2><p className="note mt-2 mb-5">{r.info}</p><Button variant="outline" size="sm" onClick={()=>{downloadCSV(`ioternak-${r.title.toLowerCase().replaceAll(' ','-')}.csv`,r.rows);setDownloaded(r.title);}}><Download/>Unduh CSV</Button></section>)}</div>{downloaded&&<p role="status" className="note mt-4">Laporan {downloaded} telah diunduh.</p>}<div className="mt-6"><OverviewStats/></div><PageFooter/></>;}
export function UsersPage(){return <><PageHeading title="Pengguna" subtitle="Profil petugas dan akses sistem IoTernak."/><section className="panel activity-panel"><PanelHeading title="Petugas Terdaftar" subtitle="Data profil administrator contoh"/><div className="table-wrap"><table className="data-table responsive-table"><thead><tr><th>Pengguna</th><th>Peran</th><th>Lokasi</th><th>Status</th></tr></thead><tbody><tr><td data-label="Pengguna"><div className="flex items-center gap-3"><span className="avatar">AP</span><span>Admin Peternakan</span></div></td><td data-label="Peran">Administrator</td><td data-label="Lokasi">Peternakan Utama</td><td data-label="Status"><div><StatusBadge tone="success" dot>Aktif</StatusBadge></div></td></tr></tbody></table></div></section><div className="panel p-6 mt-6"><p className="note">Profil ini merupakan data contoh. Pengelolaan akun dan akses pengguna belum terhubung ke layanan autentikasi.</p></div><PageFooter/></>;}
export function SettingsPage(){const [notifications,setNotifications]=useState(true);const [sound,setSound]=useState(true);const [farm,setFarm]=useState('Peternakan Utama');const [saved,setSaved]=useState(false);return <><PageHeading title="Pengaturan" subtitle="Atur preferensi tampilan dan verifikasi IoTernak."/><form className="panel settings-panel" onSubmit={e=>{e.preventDefault();setSaved(true);}}><h2 className="font-semibold text-sm mb-5">Preferensi Sistem</h2><label className="field">Nama Peternakan<input value={farm} onChange={e=>{setFarm(e.target.value);setSaved(false);}} required maxLength={80}/></label><div className="settings-row"><div><h3>Notifikasi vaksinasi</h3><p>Pengingat jadwal vaksin dan booster</p></div><Switch checked={notifications} onCheckedChange={v=>{setNotifications(v);setSaved(false);}} aria-label="Notifikasi vaksinasi"/></div><div className="settings-row"><div><h3>Suara hasil pemindaian</h3><p>Preferensi pemberitahuan reader</p></div><Switch checked={sound} onCheckedChange={v=>{setSound(v);setSaved(false);}} aria-label="Suara hasil pemindaian"/></div><div className="settings-row"><div><h3>Koneksi RFID</h3><p>Reader perangkat belum terhubung</p></div><StatusBadge tone="rfid">Mode simulasi</StatusBadge></div><p className="note my-5">Preferensi contoh disimpan selama halaman ini terbuka. Perangkat RFID dan notifikasi nyata belum terhubung.</p><Button type="submit"><Save/>Simpan Preferensi</Button>{saved&&<p role="status" className="text-success text-xs mt-3">Preferensi sesi berhasil disimpan.</p>}</form><PageFooter/></>;}
