import { useEffect, useRef, useState } from 'react';
import { ScanLine, Radio, Keyboard, ShieldCheck, CheckCircle2, LoaderCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { mockRFIDTransport, type Verification } from '@/lib/ioternak/data';
import { PanelHeading, StatusBadge, VerificationResult } from './common';
import { useLivestock } from './store';
import { Link } from '@tanstack/react-router';
export function RFIDScannerCard({full=false}:{full?:boolean}) {
  const {verify}=useLivestock();
  const [mode,setMode]=useState<'scan'|'manual'|null>(null);
  const [id,setId]=useState(''); const [error,setError]=useState('');
  const [result,setResult]=useState<Verification|null>(null); const [scanning,setScanning]=useState(false);
  const controller=useRef<AbortController|null>(null);
  useEffect(()=>()=>controller.current?.abort(),[]);
  function close() { controller.current?.abort(); setMode(null); setScanning(false); setError(''); }
  async function scan() {
    controller.current?.abort(); const current=new AbortController(); controller.current=current;
    setResult(null); setMode('scan'); setScanning(true); setError('');
    try { const tag=await mockRFIDTransport.receiveTag(current.signal); if(current.signal.aborted) return; const found=verify(tag); setResult(found || null); setScanning(false); if(!found) setError('ID RFID tidak terdaftar.'); }
    catch { if(!current.signal.aborted) { setError('Pemindaian gagal. Silakan coba lagi.'); setScanning(false); } }
  }
  function manual() { const found=verify(id); if(!found) {setError('ID RFID tidak ditemukan. Periksa kembali ID hewan.'); return;} setResult(found); setError(''); setMode('scan'); }
  return <><section className="panel"><PanelHeading title="Verifikasi RFID" subtitle="Scan tag RFID untuk memeriksa status vaksinasi hewan." action={<StatusBadge tone="rfid"><Radio size={10}/>Mode simulasi</StatusBadge>}/>{result && !mode ? <div className="p-6"><div className="flex items-center justify-between mb-4"><div><p className="text-xs text-muted-foreground">RFID terakhir</p><h3 className="text-sm font-semibold mt-1">{result.animal.id}</h3></div><StatusBadge tone="info">{result.animal.type}</StatusBadge></div><VerificationResult result={result}/><div className="scanner-buttons"><Button onClick={scan}><ScanLine/>Scan Berikutnya</Button><Button variant="outline" onClick={()=>{setId('');setMode('manual');}}>Input ID Manual</Button></div></div> : <div className="scanner-inner"><div className="scanner-graphic"><ScanLine size={39} strokeWidth={1.4}/></div><h3>Siap melakukan pemindaian</h3><p>Dekatkan tag RFID hewan untuk memulai verifikasi.</p><div className="scanner-buttons"><Button onClick={scan} className="h-10 text-[11px]"><ScanLine size={15}/>Mulai Scan RFID</Button><Button variant="outline" className="h-10 text-[11px]" onClick={()=>{setId('');setError('');setMode('manual');}}><Keyboard size={15}/>Input ID Manual</Button></div></div>}<div className="scanner-footer"><span className="flex items-center gap-2"><ShieldCheck size={12}/>Verifikasi berdasarkan data vaksinasi</span><span className="flex items-center gap-1.5"><span className="status-dot"/>Reader demo</span></div></section>{full && <div className="panel mt-6 p-6"><h2 className="text-sm font-semibold mb-3">Alur Verifikasi</h2><div className="grid grid-cols-2 sm:grid-cols-5 gap-4">{['Scan RFID','Identifikasi hewan','Periksa data vaksin','Verifikasi aturan','Hasil verifikasi'].map((t,i)=><div key={t} className="flex items-center gap-2 text-[11px] text-muted-foreground"><span className="w-6 h-6 shrink-0 rounded-full tone-rfid grid place-items-center text-[10px]">{i+1}</span>{t}</div>)}</div></div>}
  <Dialog open={mode!==null} onOpenChange={open=>{if(!open)close();}}><DialogContent className="rounded-xl max-w-[calc(100%-32px)] sm:max-w-lg"><DialogTitle>{mode==='manual'?'Input ID Manual':scanning?'Menunggu RFID...':result?'RFID berhasil dibaca':'Hasil pemindaian'}</DialogTitle><DialogDescription>{mode==='manual'?'Masukkan ID RFID hewan yang terdaftar.':scanning?'Dekatkan tag RFID hewan ke reader.':'Hasil verifikasi berdasarkan catatan vaksinasi hewan.'}</DialogDescription>{mode==='manual'? <form onSubmit={e=>{e.preventDefault();manual();}} className="modal-fields"><label className="field">ID RFID<input autoFocus placeholder="RFID-001245" value={id} onChange={e=>setId(e.target.value)} required maxLength={40}/></label>{error&&<p className="text-sm text-danger" role="alert">{error}</p>}<Button type="submit"><ScanLine/>Verifikasi RFID</Button><p className="note">Data contoh: RFID-001245 (LAYAK), RFID-001247 (DITOLAK).</p></form> : scanning?<div className="py-12 text-center"><div className="scanner-graphic scan-pulse mx-auto"><Radio size={42}/></div><div className="flex items-center justify-center gap-2 text-sm mt-8 text-rfid"><LoaderCircle size={16} className="animate-spin"/>Pemindaian simulasi</div><Button className="mt-6" variant="outline" onClick={close}>Batalkan</Button></div>: result?<><div className="flex items-center gap-2 text-success text-xs"><CheckCircle2 size={16}/>Tag RFID teridentifikasi</div><dl className="animal-facts"><div><dt>ID RFID</dt><dd>{result.animal.id}</dd></div><div><dt>Jenis Hewan</dt><dd>{result.animal.type}</dd></div><div><dt>Status Vaksin PMK</dt><dd>{result.animal.vaccinated?'Sudah Divaksin':'Belum Divaksin'}</dd></div><div><dt>Vaksin Terakhir</dt><dd>{result.animal.lastVaccine||'Belum ada catatan'}</dd></div></dl><VerificationResult result={result} large/><div className="flex justify-between gap-2 mt-2"><Button variant="outline" onClick={close}>Selesai</Button><Button asChild onClick={close}><Link to="/data-hewan/$id" params={{id:result.animal.id}}>Detail Hewan</Link></Button></div></>:<p role="alert" className="text-danger">{error}</p>}</DialogContent></Dialog></>;
}
